"""
Alert model for condition-based alerts.
Automatically generated by the alert engine.
"""
from sqlalchemy import Column, String, DateTime, ForeignKey, Text, Enum, Boolean, Float
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.database import Base
import uuid
import enum


class AlertSeverity(str, enum.Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(str, enum.Enum):
    """Types of alerts."""
    DIABETES_HIGH = "diabetes_high"
    DIABETES_LOW = "diabetes_low"
    ABNORMAL_HEART_RATE = "abnormal_heart_rate"
    LOW_OXYGEN = "low_oxygen"
    HIGH_BLOOD_PRESSURE = "high_blood_pressure"
    LOW_BLOOD_PRESSURE = "low_blood_pressure"
    ABNORMAL_TEMPERATURE = "abnormal_temperature"
    MISSED_READING = "missed_reading"
    DEVICE_MALFUNCTION = "device_malfunction"
    EMERGENCY = "emergency"


class Alert(Base):
    """
    Alerts generated by the conditions engine.
    Triggered automatically based on vital values and rules.
    """
    __tablename__ = "alerts"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    patient_id = Column(String(36), ForeignKey("patients.id"), nullable=False, index=True)
    
    # Alert details
    alert_type = Column(Enum(AlertType), nullable=False)
    severity = Column(Enum(AlertSeverity), nullable=False)
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    
    # Related data
    vital_id = Column(String(36), ForeignKey("vitals.id"), nullable=True)  # Related vital that triggered alert
    trigger_value = Column(Float, nullable=True)  # Value that triggered the alert
    
    # Status
    acknowledged = Column(Boolean, default=False, nullable=False)
    acknowledged_by = Column(String(36), ForeignKey("users.id"), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    
    resolved = Column(Boolean, default=False, nullable=False)
    resolved_by = Column(String(36), ForeignKey("users.id"), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    resolution_notes = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    
    # Relationships
    patient = relationship("Patient", backref="alerts")
    vital = relationship("Vital", backref="alerts")
    
    def __repr__(self):
        return f"<Alert {self.alert_type} - {self.severity} for {self.patient_id}>"
